### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alexstaj** [nisheth/MeFiT#2]
MBP:merged Staj$ mefit -s casper -r1 69_S69_L001_R1_001.fastq -r2 69_S69_L001_R2_001.fastq -p casper.params2 -nonovlp -n 15 -avgq 20
Traceback (most recent call last):
  File "/Users/Staj/tools/bin/mefit", line 310, in <module>
    if **name** == "**main**": main() 
  File "/Users/Staj/tools/bin/mefit", line 261, in main
    qf_stats = qf(casperovlpfastq, casperforleft, casperrevleft,  non_ovlp_flag, ovlpfastq, nonovlpfastq, ovlphqfastq, nonovlphqfastq, qfmethod, threshold)
  File "/Users/Staj/tools/bin/mefit", line 171, in qf
    for r1,r2 in zip(HTSeq.FastqReader(casperforleft),HTSeq.FastqReader(casperrevleft)):
  File "/Library/Python/2.7/site-packages/HTSeq/**init**.py", line 374, in **iter**
    id1  = fin.next()
  File "/Library/Python/2.7/site-packages/HTSeq/**init**.py", line 51, in **iter**
    lines = open( self.fos )
IOError: [Errno 2] No such file or directory: './casper_for_left.fastq'

contents of log file:
# 

[CASPER] Context-Aware Scheme for Paired-End Read

  Input Files
     -  Forward file     : 69_S69_L001_R1_001.fastq
     -  Reverse file     : 69_S69_L001_R2_001.fastq

  Parameters
     -  Number of threads for parallel processing : 4
     -  K-mer size                                : 17
     -  Threshold for difference of quality score : 19
     -  Threshold for mismatching ratio           : 0.5
     -  Minimum length of overlap                 : 10
     -  Using Jellyfish                           : true

  K-mers : Jellyfish
     -  jellyfish count -m 17 -L 2 -o casperjellykmer -c 3 -s 10M -t 4 69_S69_L001_R1_001.fastq
     -  jellyfish count -m 17 -L 2 -o casperjellykmer -c 3 -s 10M -t 4 69_S69_L001_R2_001.fastq

  Output Files
     -  Merged output file            : casper.fastq

  Merging Result Statistics
     -  Total number of reads     :      83257
     -  Number of merged reads    :      19128 (22.97%)
     -  Number of unmerged reads  :      64129 (77.03%)
#      -  TIME for total processing :     12.745 sec

produced files casper.casper.log, casper.fastq (23mb with ~19,000 reads), casper.nonovlp.fasatq (zero bytes), casper.nonovlp.hq.fastq (zero bytes), casper.ovlp.fastq (23mb), casper.ovlp.hq.fastq (23mb), casper.params2 (made a copy of the default casper.params file and put it in my reads folder)

don't know why the log file has different parameters than my casper.params2 file.

**Comment by alexstaj** [comment]
repeated same thing with new command but same kind of errors:

MBP:merged Staj$ mefit -s meat1 -r1 69_S69_L001_R1_001.fastq -r2 69_S69_L001_R2_001.fastq -avgq 20
Traceback (most recent call last):
  File "/Users/Staj/tools/bin/mefit", line 310, in <module>
    if **name** == "**main**": main() 
  File "/Users/Staj/tools/bin/mefit", line 261, in main
    qf_stats = qf(casperovlpfastq, casperforleft, casperrevleft,  non_ovlp_flag, ovlpfastq, nonovlpfastq, ovlphqfastq, nonovlphqfastq, qfmethod, threshold)
  File "/Users/Staj/tools/bin/mefit", line 142, in qf
    for r in HTSeq.FastqReader(casperovlpfastq):
  File "/Library/Python/2.7/site-packages/HTSeq/**init**.py", line 374, in **iter**
    id1  = fin.next()
  File "/Library/Python/2.7/site-packages/HTSeq/**init**.py", line 51, in **iter**
    lines = open( self.fos )
IOError: [Errno 2] No such file or directory: './meat1.fastq'

**Comment by nisheth** [comment]
We will look into this and update you soon. Thanks for evaluating and using this tool.  Please feel free to give us the feedback.
