### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by hackerzone85** [nisheth/MeFiT#3]
```
$mefit -s sample -r1 sample_R1.fastq -r2 sample_R2.fastq -p casper.params -nonovlp -n 15 -meep 1.0
Traceback (most recent call last):
  File "./mefit", line 310, in <module>
    if __name__ == "__main__": main() 
  File "./mefit", line 237, in main
    merge_stats = merge_CASPER(fwd_file, rev_file, outname, logfile) 
  File "./mefit", line 109, in merge_CASPER
    casperstatsList = [totreads, merged, "%.2f" % ((merged*100.0)/totreads), unmerged, "%.2f" % ((unmerged*100.0)/totreads)] 
ZeroDivisionError: float division by zero
```

**Comment by Leo-alves** [comment]
Same thing here. it looks like they are not supporting the code anymore. By the way, I could solve the "division by zero" issue. At least something.
For that you could write in the code (line 109 right after OLF.close( )):
if totreads == 0:
                totreads = 0.999999999999999999999999
#that block substitutes totreads value 0 for almost zero and allow code to run after. 
But still the other erros will appear. It's a shame because I really would like to use mefit
